apiVersion: v1
kind: Namespace
metadata:
  name: rajvijeyaram
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-html
  namespace: rajvijeyaram
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Status</title>
    </head>
    <body style="background-color: #FF00FF; display:flex; justify-content:center; align-items:center; height:100vh;">
      <h1>Successful</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-site
  namespace: rajvijeyaram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: portfolio-html
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: rajvijeyaram
spec:
  selector:
    app: portfolio-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80