apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rajvijeyaram-ingress
  namespace: rajvijeyaram
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: portfolio.rajvijeyaram.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 80
  - host: forgejo.rajvijeyaram.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgejo-service
            port:
              number: 3000
